"""'init'

Revision ID: d92af5695aee
Revises: eb3bd4023a85
Create Date: 2017-01-04 15:32:39.087000

"""

# revision identifiers, used by Alembic.
revision = 'd92af5695aee'
down_revision = 'eb3bd4023a85'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=120), nullable=True))
    op.drop_column('user', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('user', 'password')
    ### end Alembic commands ###
